<?php

declare(strict_types=1);

namespace Mitsuki\ORM\Command;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Filesystem\Path;

/**
 * Command responsible for clearing the Repository metadata cache.
 * * It removes the physical mapping file generated by the Repository 
 * reflection logic to allow fresh discovery of entity classes.
 *
 * @author Zgenius matondo <zgeniuscoders@gmail.com>
 * @package Mitsuki\ORM\Command
 */
#[AsCommand(
    name: 'repository:clear', 
    description: 'Clears the repository metadata cache file'
)]
class RepositoryClearCommand extends Command
{
    private Filesystem $filesystem;

    /**
     * @param string $cachePath The same directory path used by your Repositories
     */
    public function __construct(private string $cachePath)
    {
        parent::__construct();
        $this->filesystem = new Filesystem();
    }

    /**
     * Executes the cache clearing process.
     *
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int 0 for success, 1 for failure
     */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $cacheFile = Path::join($this->cachePath, 'mitsuki_repo_map.php');

        $io->title('Mitsuki ORM: Clear Repository Cache');

        if (!$this->filesystem->exists($cacheFile)) {
            $io->info('No repository cache file found. Nothing to clear.');
            return Command::SUCCESS;
        }

        try {
            $this->filesystem->remove($cacheFile);
            $io->success('Repository metadata cache has been cleared successfully.');
            return Command::SUCCESS;
        } catch (\Exception $e) {
            $io->error('Failed to clear repository cache: ' . $e->getMessage());
            return Command::FAILURE;
        }
    }
}